=== Javierfernandezrubio/javierfernandezrubio2.github.io/LM/temas/Ejercicios en clase/XML/persona.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,mayor_de_edad?,ciudad)>
<!ATTLIST persona formapago (Contado|Tarjeta) "Contado">
<!ATTLIST persona dni ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mayor_de_edad EMPTY>
<!ELEMENT ciudad (#PCDATA)>

=== Javierfernandezrubio/javierfernandezrubio2.github.io/web-antigua/LM/temas/PracticasTemaXML/XML/EjemploPersona.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "persona.dtd">
<personas>
    <persona dni="12345678-A">
        <nombre>Javier Fernández</nombre>
        <mayor_de_edad></mayor_de_edad>
        <ciudad>Córdoba</ciudad>
    </persona>
    <persona formapago="Tarjeta" dni="12345679-B">
        <nombre>Dora</nombre>
        <ciudad>Córdoba</ciudad>
    </persona>
</personas>
