=== Javierfernandezrubio/javierfernandezrubio2.github.io/Practicas/practicasXSL/actividades/actividad3.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="alumnos">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="alumno" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="xs:string" name="nombre"/>
            <xs:element type="xs:string" name="apellidos"/>
            <xs:element type="xs:string" name="curso"/>
            <xs:element name="asignaturas">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="programacion">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element type="xs:byte" name="nota"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="lenguaje_marcas">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element type="xs:byte" name="nota"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="bases_datos" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element type="xs:byte" name="nota"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="sistemas_informaticos" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element type="xs:byte" name="nota"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="entornos" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element type="xs:byte" name="nota"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="id" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== Javierfernandezrubio/javierfernandezrubio2.github.io/Practicas/practicasXSL/actividades/actividad3.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-model href="actividad3.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="actividad3.xsd">
    <alumno id="a1">
        <nombre>Javier</nombre>
        <apellidos>Fernández Rubio</apellidos>
        <curso>1º DAW</curso>
        <asignaturas>
            <programacion>
                <nota>8</nota>
            </programacion>
            <lenguaje_marcas>
                <nota>7</nota>
            </lenguaje_marcas>
        </asignaturas>
    </alumno>

    <alumno id="a2">
        <nombre>David</nombre>
        <apellidos>Garcia Rosal</apellidos>
        <curso>1º DAW</curso>
        <asignaturas>
            <programacion>
                <nota>5</nota>
            </programacion>
            <lenguaje_marcas>
                <nota>6</nota>
            </lenguaje_marcas>
            <bases_datos>
                <nota>4</nota>
            </bases_datos>
            <sistemas_informaticos>
                <nota>8</nota>
            </sistemas_informaticos>
            <entornos>
                <nota>7</nota>
            </entornos>
        </asignaturas>
    </alumno>

</alumnos>
